/** Embedded dependency-free UI: table-first explorer + preserved list view. */
export const INDEX_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Agent Annotation Hub</title>
<style>
:root{--bg:#f5f6f8;--surface:#fff;--ink:#1c2024;--muted:#667085;--line:#e2e6eb;--accent:#2563eb;--accent-soft:#eff6ff;--ok:#16a34a;--bad:#dc2626;--bad-soft:#fef2f2;--warn:#b45309;--chip:#eef2f7;--head:#f8fafc}
@media(prefers-color-scheme:dark){:root{--bg:#101317;--surface:#1a1f26;--ink:#edf0f4;--muted:#a4adba;--line:#2d3540;--accent:#60a5fa;--accent-soft:#17243a;--ok:#4ade80;--bad:#f87171;--bad-soft:#351b20;--warn:#fbbf24;--chip:#252c35;--head:#151a20}}
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--bg);color:var(--ink);font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select,a{font:inherit}header{position:sticky;top:0;z-index:5;background:color-mix(in srgb,var(--surface) 95%,transparent);border-bottom:1px solid var(--line);padding:13px 20px;display:flex;align-items:center;justify-content:space-between;gap:16px}h1{margin:0;font-size:16px}.meta,.sub{color:var(--muted);font-size:12px}main{max-width:1600px;margin:auto;padding:20px}.banner{display:none;border:1px solid var(--bad);color:var(--bad);background:var(--bad-soft);border-radius:9px;padding:9px 12px;margin-bottom:12px}.banner.warn{border-color:var(--warn);color:var(--warn)}
.toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px}.segmented{display:inline-flex;border:1px solid var(--line);border-radius:9px;overflow:hidden;background:var(--surface)}.segmented button{border:0;border-right:1px solid var(--line);padding:8px 13px;background:transparent;color:var(--muted);cursor:pointer}.segmented button:last-child{border-right:0}.segmented button.active{background:var(--accent-soft);color:var(--accent);font-weight:650}.bulk{display:flex;gap:7px;align-items:center}.btn{min-height:36px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--ink);padding:6px 11px;cursor:pointer}.btn:hover:not(:disabled){border-color:var(--accent);color:var(--accent)}.btn.danger:hover:not(:disabled){border-color:var(--bad);color:var(--bad)}.btn:disabled{opacity:.45;cursor:not-allowed}
.filters{display:grid;grid-template-columns:minmax(170px,1.5fr) repeat(5,minmax(120px,1fr)) 110px 110px auto;gap:9px;align-items:end;margin-bottom:14px;padding:13px;background:var(--surface);border:1px solid var(--line);border-radius:11px}.field{display:grid;gap:4px;min-width:0}.field label{font-size:11px;color:var(--muted);font-weight:600}.field input,.field select{width:100%;height:36px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:var(--ink);padding:0 9px}.clear{height:36px}
.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:11px;background:var(--surface)}table{border-collapse:separate;border-spacing:0;width:100%;min-width:1540px}thead{position:sticky;top:0;z-index:2}th{background:var(--head);font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.035em;text-align:left;border-bottom:1px solid var(--line);padding:9px 8px;white-space:nowrap}th.sortable{cursor:pointer;user-select:none}th.sortable:hover{color:var(--accent)}th[data-active]::after{content:attr(data-dir);margin-left:5px;color:var(--accent)}td{padding:9px 8px;border-bottom:1px solid var(--line);vertical-align:middle;white-space:nowrap}tbody tr:last-child td{border-bottom:0}tbody tr:hover{background:color-mix(in srgb,var(--accent-soft) 42%,transparent)}.check{width:16px;height:16px;accent-color:var(--accent)}.tool{font-weight:700}.review{display:grid;gap:1px;max-width:280px}.review strong,.review span{overflow:hidden;text-overflow:ellipsis}.review strong{font-size:12.5px}.review span{font-size:11px;color:var(--muted)}.kind{display:grid;gap:1px}.kind strong{font-size:12.5px}.kind span{font-size:11px;color:var(--muted)}.health{display:inline-flex;align-items:center;gap:6px}.dot{width:7px;height:7px;border-radius:50%;background:var(--muted)}.dot.ok{background:var(--ok)}.dot.unreachable{background:var(--bad)}.mono{font:11.5px ui-monospace,SFMono-Regular,Menlo,monospace}.truncate{max-width:220px;overflow:hidden;text-overflow:ellipsis}.num{text-align:right;font-variant-numeric:tabular-nums}.actions{display:flex;gap:5px}.icon{width:31px;height:31px;display:grid;place-items:center;border:1px solid var(--line);border-radius:7px;background:var(--surface);color:var(--muted);cursor:pointer;text-decoration:none}.icon:hover{border-color:var(--accent);color:var(--accent)}.icon.close:hover{border-color:var(--bad);color:var(--bad)}
#list-view{display:none}.tool-section{margin:22px 0 28px}.section-head{display:flex;align-items:baseline;gap:8px;margin-bottom:8px}.section-head h2{font-size:14px;margin:0}.cards{display:grid;gap:8px}.card{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:12px 14px}.card-title{font-weight:650}.chips{display:flex;flex-wrap:wrap;gap:5px;margin:5px 0}.chip{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;padding:2px 7px;border-radius:999px;background:var(--chip);color:var(--muted)}.chip.kindchip{color:var(--accent)}.dir{display:block;color:var(--muted);font:11.5px ui-monospace,SFMono-Regular,Menlo,monospace;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.empty{display:none;border:1px dashed var(--line);border-radius:11px;padding:30px;text-align:center;color:var(--muted)}
dialog{width:min(450px,calc(100vw - 32px));border:1px solid var(--line);border-radius:13px;padding:0;color:var(--ink);background:var(--surface);box-shadow:0 18px 55px #0005}dialog::backdrop{background:#050a1299}.dialog-body{padding:21px}.dialog-body h2{margin:0 0 8px;font-size:18px}.dialog-body p{margin:0;color:var(--muted)}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;border-top:1px solid var(--line);padding:13px 21px}footer{text-align:center;color:var(--muted);font-size:12px;padding:18px}
@media(max-width:1100px){.filters{grid-template-columns:repeat(3,minmax(130px,1fr))}.filters .search{grid-column:span 2}}@media(max-width:650px){main{padding:12px}.filters{grid-template-columns:1fr 1fr}.filters .search{grid-column:1/-1}.toolbar{align-items:flex-start;flex-direction:column}.card{grid-template-columns:auto minmax(0,1fr)}.card .actions{grid-column:2}}
</style></head><body>
<header><h1>Agent Annotation Hub</h1><div class="meta"><span id="count">0 live</span> · updated <span id="when">–</span></div></header>
<main><div id="err" class="banner" role="alert"></div><div id="warn" class="banner warn"></div>
<div class="toolbar"><div class="segmented" aria-label="View"><button id="show-table" class="active" type="button">Table</button><button id="show-list" type="button">List (classic)</button></div><div class="bulk"><span id="selected-count" class="sub">0 selected</span><button id="open-selected" class="btn" disabled>Open selected</button><button id="close-selected" class="btn danger" disabled>Close selected</button></div></div>
<div class="filters" aria-label="Session filters">
<div class="field search"><label for="search">Search / PID / parent PID</label><input id="search" type="search" placeholder="PID, target, repository…"></div>
<div class="field"><label for="filter-tool">Tool</label><select id="filter-tool"><option value="">All tools</option></select></div>
<div class="field"><label for="filter-kind">Review kind</label><select id="filter-kind"><option value="">All kinds</option></select></div>
<div class="field"><label for="filter-repo">Repository</label><select id="filter-repo"><option value="">All repositories</option></select></div>
<div class="field"><label for="filter-branch">Branch</label><select id="filter-branch"><option value="">All branches</option></select></div>
<div class="field"><label for="filter-cwd">Working directory</label><select id="filter-cwd"><option value="">All CWDs</option></select></div>
<div class="field"><label for="min-comments">Min comments</label><input id="min-comments" type="number" min="0" placeholder="Any"></div>
<div class="field"><label for="min-round">Min round</label><input id="min-round" type="number" min="1" placeholder="Any"></div>
<button id="clear-filters" class="btn clear" type="button">Clear</button>
</div>
<div id="table-view" class="table-wrap"><table><thead><tr>
<th><input id="select-all" class="check" type="checkbox" aria-label="Select all visible"></th>
<th class="sortable" data-key="tool">Tool</th><th class="sortable" data-key="subject">Review</th><th class="sortable" data-key="kind">Kind</th><th class="sortable" data-key="repository">Repository</th><th class="sortable" data-key="branch">Branch</th><th class="sortable" data-key="cwd">CWD</th><th class="sortable" data-key="pid">PID</th><th class="sortable" data-key="parentAgentPid">Parent PID</th><th class="sortable num" data-key="commentCount">Comments</th><th class="sortable num" data-key="reviewRound">Round</th><th class="sortable" data-key="startedAt">Started</th><th>Health</th><th>Actions</th>
</tr></thead><tbody id="table-body"></tbody></table></div>
<div id="list-view"></div><div id="empty" class="empty">No sessions match the current filters.</div></main>
<footer>Loopback only · classifies launch metadata, never reads review contents</footer>
<dialog id="close-dialog"><div class="dialog-body"><h2>Close session?</h2><p id="close-copy"></p></div><div class="dialog-actions"><button id="cancel-close" class="btn">Cancel</button><button id="confirm-close" class="btn danger">Close session</button></div></dialog>
<script>(function(){"use strict";
var byId=function(id){return document.getElementById(id)},tableBody=byId("table-body"),tableView=byId("table-view"),listView=byId("list-view"),empty=byId("empty"),errBox=byId("err"),warnBox=byId("warn"),countEl=byId("count"),whenEl=byId("when"),selected=new Set(),data=null,pending=[],view="table",sort={key:"tool",dir:1};
var filterIds=["search","filter-tool","filter-kind","filter-repo","filter-branch","filter-cwd","min-comments","min-round"];
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function rel(iso){if(!iso)return"–";var t=Date.parse(iso),s=Math.max(0,(Date.now()-t)/1000);if(!isFinite(t))return iso;if(s<5)return"now";if(s<60)return Math.floor(s)+"s";if(s<3600)return Math.floor(s/60)+"m";if(s<86400)return Math.floor(s/3600)+"h";return Math.floor(s/86400)+"d"}
function basename(v){return String(v||"").split("/").filter(Boolean).pop()||""}
function reviewSubject(s){var target=String(s.target||"");if(target&&target.indexOf("http://")!==0&&target.indexOf("https://")!==0)return basename(target);if(s.kind==="code-review")return s.branch||s.repository||"Code changes";if(s.target)return s.target;return s.label||s.project||s.branch||s.repository||basename(s.cwd)||s.id}
function reviewContext(s){if(s.kind==="code-review")return s.repository||s.cwd||"";return s.branch||s.repository||s.category||""}
function title(s){return reviewSubject(s)}
function prettyKind(v){return String(v||"Unknown").split("-").map(function(w){return w.charAt(0).toUpperCase()+w.slice(1)}).join(" ")}
function allText(s){return [s.id,s.tool,s.category,s.kind,s.target,s.repository,s.repoRoot,s.branch,s.cwd,s.pid,s.parentAgentPid,s.parentAgentGroup,s.mode,s.label,s.project].join(" ").toLowerCase()}
function filters(){return{q:byId("search").value.trim().toLowerCase(),tool:byId("filter-tool").value,kind:byId("filter-kind").value,repo:byId("filter-repo").value,branch:byId("filter-branch").value,cwd:byId("filter-cwd").value,comments:byId("min-comments").value,round:byId("min-round").value}}
function visible(){var f=filters(),rows=(data&&data.sessions||[]).filter(function(s){return(!f.q||allText(s).includes(f.q))&&(!f.tool||s.tool===f.tool)&&(!f.kind||s.kind===f.kind)&&(!f.repo||(s.repository||"")===f.repo)&&(!f.branch||(s.branch||"")===f.branch)&&(!f.cwd||(s.cwd||"")===f.cwd)&&(!f.comments||(s.commentCount!=null&&s.commentCount>=Number(f.comments)))&&(!f.round||(s.reviewRound!=null&&s.reviewRound>=Number(f.round)))});return rows.sort(function(a,b){var av=sort.key==="subject"?reviewSubject(a):a[sort.key],bv=sort.key==="subject"?reviewSubject(b):b[sort.key];if(av==null&&bv!=null)return 1;if(bv==null&&av!=null)return-1;if(sort.key==="startedAt")return sort.dir*((Date.parse(av)||0)-(Date.parse(bv)||0));if(typeof av==="number"&&typeof bv==="number")return sort.dir*(av-bv);var c=String(av||"").localeCompare(String(bv||""));if(c===0&&sort.key==="tool")return(Date.parse(b.startedAt)||0)-(Date.parse(a.startedAt)||0);return sort.dir*c})}
function actionHtml(s){return'<div class="actions">'+(s.url?'<a class="icon" href="'+esc(s.url)+'" target="_blank" rel="noopener" title="Open">↗</a>':'<span class="icon" title="No safe URL">—</span>')+'<button class="icon close" data-close="'+esc(s.id)+'" title="Close">×</button></div>'}
function renderTable(rows){tableBody.innerHTML=rows.map(function(s){return'<tr data-session-id="'+esc(s.id)+'" class="'+(s.url?'openable':'')+'"><td><input class="check row-check" data-id="'+esc(s.id)+'" type="checkbox" '+(selected.has(s.id)?"checked":"")+'></td><td class="tool">'+esc(s.tool)+'</td><td title="'+esc(s.target||reviewSubject(s))+'"><div class="review"><strong>'+esc(reviewSubject(s))+'</strong><span>'+esc(reviewContext(s))+'</span></div></td><td><div class="kind"><strong>'+esc(prettyKind(s.kind))+'</strong><span>'+esc(s.category)+'</span></div></td><td class="truncate" title="'+esc(s.repoRoot||s.repository||"")+'">'+esc(s.repository||"—")+'</td><td class="mono">'+esc(s.branch||"—")+(s.worktree?' · wt':'')+'</td><td class="mono truncate" title="'+esc(s.cwd||"")+'">'+esc(s.cwd||"—")+'</td><td class="mono">'+esc(s.pid||"—")+'</td><td class="mono" title="'+esc(s.parentAgentGroup||"")+'">'+esc(s.parentAgentPid||"—")+'</td><td class="num">'+esc(s.commentCount==null?"—":s.commentCount)+'</td><td class="num">'+esc(s.reviewRound==null?"—":s.reviewRound)+'</td><td title="'+esc(s.startedAt||"")+'">'+rel(s.startedAt)+'</td><td><span class="health"><span class="dot '+esc(s.health)+'"></span>'+esc(s.health)+'</span></td><td>'+actionHtml(s)+'</td></tr>'}).join("");bindRows(rows)}
function card(s){return'<article class="card '+(s.url?'openable':'')+'" data-session-id="'+esc(s.id)+'"><input class="check row-check" data-id="'+esc(s.id)+'" type="checkbox" '+(selected.has(s.id)?"checked":"")+'><div><div class="card-title">'+esc(title(s))+'</div><div class="chips"><span class="chip kindchip">'+esc(prettyKind(s.kind))+'</span><span class="chip">'+esc(s.category)+'</span>'+(s.branch?'<span class="chip">'+esc(s.branch)+(s.worktree?' · worktree':'')+'</span>':'')+(s.pid?'<span class="chip">pid '+s.pid+'</span>':'')+(s.parentAgentPid?'<span class="chip">parent '+s.parentAgentPid+'</span>':'')+(s.commentCount!=null?'<span class="chip">comments '+s.commentCount+'</span>':'')+(s.reviewRound!=null?'<span class="chip">round '+s.reviewRound+'</span>':'')+'</div><span class="sub">'+esc(s.target||s.label||s.mode||"")+'</span><code class="dir">'+esc(s.cwd||"")+'</code></div>'+actionHtml(s)+'</article>'}
function renderList(rows){var tools=["crit","plannotator"];listView.innerHTML=tools.map(function(tool){var items=rows.filter(function(s){return s.tool===tool});return'<section class="tool-section"><div class="section-head"><h2>'+esc(tool==="crit"?"Crit":"Plannotator")+'</h2><span class="sub">'+items.length+' sessions</span></div><div class="cards">'+items.map(card).join("")+'</div></section>'}).join("");bindRows(rows)}
function bindRows(rows){document.querySelectorAll(".row-check").forEach(function(el){el.addEventListener("change",function(){if(el.checked)selected.add(el.dataset.id);else selected.delete(el.dataset.id);updateBulk(rows)})});document.querySelectorAll("[data-close]").forEach(function(el){el.addEventListener("click",function(){var s=(data.sessions||[]).find(function(x){return x.id===el.dataset.close});if(s)askClose([s])})});document.querySelectorAll("[data-session-id].openable").forEach(function(el){el.addEventListener("dblclick",function(event){if(event.target.closest("a,button,input,select,textarea,label"))return;var s=(data.sessions||[]).find(function(x){return x.id===el.dataset.sessionId});if(s&&s.url)window.open(s.url,"_blank","noopener")})});updateBulk(rows)}
function updateBulk(rows){var chosen=rows.filter(function(s){return selected.has(s.id)});byId("selected-count").textContent=chosen.length+" selected";byId("open-selected").disabled=!chosen.some(function(s){return s.url});byId("close-selected").disabled=!chosen.length;var all=byId("select-all");all.checked=!!rows.length&&chosen.length===rows.length;all.indeterminate=chosen.length>0&&chosen.length<rows.length}
function render(){if(!data)return;var live=new Set((data.sessions||[]).map(function(s){return s.id}));selected.forEach(function(id){if(!live.has(id))selected.delete(id)});var rows=visible();countEl.textContent=(data.sessions||[]).length+" live · "+rows.length+" shown";whenEl.textContent=rel(data.generatedAt);tableView.style.display=view==="table"&&rows.length?"block":"none";listView.style.display=view==="list"&&rows.length?"block":"none";empty.style.display=rows.length?"none":"block";if(view==="table")renderTable(rows);else renderList(rows);document.querySelectorAll("th.sortable").forEach(function(th){th.removeAttribute("data-active");th.removeAttribute("data-dir");if(th.dataset.key===sort.key){th.setAttribute("data-active","");th.setAttribute("data-dir",sort.dir===1?"▲":"▼")}})}
function fillSelect(id,values,label){var el=byId(id),old=el.value;el.innerHTML='<option value="">All '+label+'</option>'+Array.from(new Set(values.filter(Boolean))).sort().map(function(v){return'<option value="'+esc(v)+'">'+esc(id==="filter-kind"?prettyKind(v):v)+'</option>'}).join("");el.value=old}
function hydrateFilters(){var ss=data.sessions||[];fillSelect("filter-tool",ss.map(function(s){return s.tool}),"tools");fillSelect("filter-kind",ss.map(function(s){return s.kind}),"kinds");fillSelect("filter-repo",ss.map(function(s){return s.repository}),"repositories");fillSelect("filter-branch",ss.map(function(s){return s.branch}),"branches");fillSelect("filter-cwd",ss.map(function(s){return s.cwd}),"CWDs")}
function askClose(items){pending=items;byId("close-copy").textContent=items.length===1?'Terminate “'+title(items[0])+'” (PID '+items[0].pid+')? Unsaved review state may be lost.':'Terminate '+items.length+' selected sessions? Unsaved review state may be lost.';byId("close-dialog").showModal()}
async function refresh(){try{var rs=await Promise.all([fetch("/api/sessions",{cache:"no-store"}),fetch("/api/health",{cache:"no-store"})]),r=rs[0],hr=rs[1];if(!r.ok)throw Error("HTTP "+r.status);data=await r.json();var health=hr.ok?await hr.json():null,compatWarnings=[];if(health&&health.compatibility)Object.keys(health.compatibility).forEach(function(tool){var c=health.compatibility[tool];if(c.status!=="verified")compatWarnings.push(tool+" "+(c.installed||"unavailable")+" is not verified against "+c.verifiedAgainst)});var warnings=[data.lastError].filter(Boolean).concat(compatWarnings);warnBox.style.display=warnings.length?"block":"none";warnBox.textContent=warnings.join(" · ");hydrateFilters();render();errBox.style.display="none"}catch(e){errBox.textContent="Cannot reach hub API: "+e.message;errBox.style.display="block"}}
filterIds.forEach(function(id){byId(id).addEventListener(id==="search"||id.indexOf("min-")===0?"input":"change",render)});byId("clear-filters").addEventListener("click",function(){filterIds.forEach(function(id){byId(id).value=""});render()});byId("show-table").addEventListener("click",function(){view="table";this.classList.add("active");byId("show-list").classList.remove("active");render()});byId("show-list").addEventListener("click",function(){view="list";this.classList.add("active");byId("show-table").classList.remove("active");render()});document.querySelectorAll("th.sortable").forEach(function(th){th.addEventListener("click",function(){if(sort.key===th.dataset.key)sort.dir*=-1;else{sort.key=th.dataset.key;sort.dir=1}render()})});byId("select-all").addEventListener("change",function(){visible().forEach(function(s){if(byId("select-all").checked)selected.add(s.id);else selected.delete(s.id)});render()});byId("open-selected").addEventListener("click",function(){visible().filter(function(s){return selected.has(s.id)&&s.url}).forEach(function(s){window.open(s.url,"_blank","noopener")})});byId("close-selected").addEventListener("click",function(){askClose(visible().filter(function(s){return selected.has(s.id)}))});byId("cancel-close").addEventListener("click",function(){byId("close-dialog").close()});byId("confirm-close").addEventListener("click",async function(){this.disabled=true;for(var i=0;i<pending.length;i++){var s=pending[i],r=await fetch("/api/sessions/"+encodeURIComponent(s.id)+"/close",{method:"POST",headers:{"x-annotation-hub-action":"close-session"}});if(r.ok)selected.delete(s.id)}this.disabled=false;byId("close-dialog").close();pending=[];setTimeout(refresh,250)});
setInterval(refresh,2000);document.addEventListener("visibilitychange",function(){if(document.visibilityState==="visible")refresh()});refresh();
})();</script></body></html>`;
